// Composition root for the 90 Waypoint Map app (docs/adr/0003).
//
// This is the ONLY place that wires the pure domain/application core to the DOM/Canvas adapters and
// chooses the production driven ports. The hexagon's two real boundaries — randomness and rendering —
// plus the cooperative-yield boundary are all injected here:
//
//   • RandomSource — an entropy-seeded SeededRandom, produced FRESH per generation via a factory so
//     each Generate starts an independent deterministic stream. US-022 layers the `?seed=` URL
//     override on top of this default without touching the adapter or the core.
//   • Renderer     — the Canvas 2D CanvasRenderer, bound to the page's <canvas>.
//   • Yield        — a MACROTASK yield (see {@link productionYield}) so the browser can paint the
//     loading overlay and animate its CSS spinner between the generator's synchronous placement batches.
//
// On load it auto-generates a walk so the canvas is never blank (US-021 AC2). The wiring is exposed as
// {@link bootstrap} (plus the port + factory it injects) so the headless gate
// (scripts/verify-main.mjs) can drive the same composition with fakes; the auto-run at the bottom is
// guarded by a `typeof document` check so importing this module in Node has no side effects.
import { RandomSource } from "./domain/random-source.js";
import { SeededRandom } from "./domain/seeded-random.js";
import { GenerateWalk } from "./application/generate-walk.js";
import { ClearWalk } from "./application/clear-walk.js";
import { Yield } from "./application/yield-port.js";
import { CanvasRenderer } from "./adapters/canvas-renderer.js";
import { CONTROL_IDS, DomControls } from "./adapters/dom-controls.js";

/**
 * Production {@link Yield} port.
 *
 * `yieldToEventLoop` MUST be a MACROTASK, not a microtask: {@link GenerateWalk} awaits it between
 * generation batches so the browser can paint the loading overlay and animate its (pure-CSS) spinner.
 * A microtask (`queueMicrotask` / `Promise.resolve`) drains within the SAME event-loop turn, BEFORE the
 * browser ever yields to its render/paint queue — so paint would be starved and the overlay would never
 * appear. `setTimeout(…, 0)` is the simplest macrotask: it hands control back to the event loop, after
 * which the browser is free to render before the next synchronous chunk of placement work runs.
 */
export const productionYield: Yield = {
  yieldToEventLoop(): Promise<void> {
    return new Promise((resolve) => {
      setTimeout(() => resolve(), 0);
    });
  },
};

/**
 * Production {@link RandomSource} factory: a fresh, entropy-seeded {@link SeededRandom} per call.
 *
 * It is a FACTORY (not a single shared instance) because each Generate must start an independent
 * deterministic stream — a shared mutable source would make walk N depend on every prior draw, breaking
 * US-022's single-seed reproducibility. `new SeededRandom()` with no argument seeds from entropy;
 * US-022 layers the `?seed=` override on top.
 */
export function createRandom(): RandomSource {
  return new SeededRandom();
}

/** What {@link bootstrap} hands back: the wired controls and the first (auto-generate-on-load) walk. */
export interface Bootstrapped {
  /** The wired DOM controls — interactive once this returns (Generate / Clear / toggles / Print). */
  readonly controls: DomControls;
  /**
   * The auto-generate-on-load promise (US-021 AC2). Resolved by `generate()`'s own `finally`, so it
   * settles on success, on the bounded failure signal, and on a throw (which `generate` surfaces — it
   * is logged here so it never becomes an unhandled rejection). Awaitable by the headless gate.
   */
  readonly autoGenerated: Promise<void>;
}

/**
 * Wire the whole app and auto-generate the first walk.
 *
 * Resolves the <canvas>, builds the Canvas renderer, the {@link GenerateWalk} / {@link ClearWalk} use
 * cases (injecting {@link productionYield}) and the {@link DomControls} (injecting the renderer + the
 * entropy-seeded {@link createRandom} factory), then kicks off a generation so the canvas is never blank
 * on first load (US-021 AC2).
 *
 * @param doc the document to resolve the page chrome from; defaults to the live `document`. The headless
 *            gate passes a fake so the same composition can be exercised in Node.
 */
export function bootstrap(doc: Document = document): Bootstrapped {
  // Resolve the canvas explicitly (rather than via `instanceof HTMLCanvasElement`, which would need the
  // DOM global at runtime) so the renderer can bind to it; CanvasRenderer throws if it isn't a real
  // canvas (no 2D context). fromDocument re-resolves it (and the rest of the chrome) for its listeners.
  const canvasEl = doc.getElementById(CONTROL_IDS.canvas);
  if (canvasEl === null) {
    throw new Error(`main: required canvas #${CONTROL_IDS.canvas} not found in the document`);
  }
  const renderer = new CanvasRenderer(canvasEl as HTMLCanvasElement);
  const generateWalk = new GenerateWalk(productionYield);
  const clearWalk = new ClearWalk(renderer);
  const controls = DomControls.fromDocument(
    { generateWalk, clearWalk, renderer, createRandom },
    doc
  );

  // Auto-generate on first load so the canvas is never blank (US-021 AC2). `generate()` owns its own
  // overlay/button try/finally and rethrows; own the rejection here so a stray failure can't become an
  // unhandled promise rejection (the on-screen error overlay already covers the bounded failure signal).
  const autoGenerated = controls.generate().catch((err: unknown) => {
    console.error(err);
  });
  return { controls, autoGenerated };
}

// Auto-run in the browser only. The entry is loaded with `type="module"` (deferred), so the DOM is
// already parsed by the time this runs; the readyState check is a belt-and-braces fallback. The
// `typeof document` guard keeps importing this module in Node (the headless gate) side-effect-free.
if (typeof document !== "undefined") {
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", () => {
      bootstrap();
    });
  } else {
    bootstrap();
  }
}
